model_sizes = {
    "01-ai/Yi-Coder-9B-Chat":                    "8.8B",
    "google/codegemma-7b-it":                    "8.5B",
    "Qwen/Qwen3-4B":                             "4B",
    "Qwen/Qwen3-8B":                             "8B",
    "Qwen/Qwen3-32B":                            "32.8B",
    "bigcode/starcoder2-15b-instruct-v0.1":      "15B",
    "codellama/CodeLlama-70b-Python-hf":         "70B",
    "codellama/CodeLlama-34b-Instruct-hf":       "34B",
    "microsoft/Phi-3-mini-128k-instruct":        "3.8B",
    "microsoft/Phi-3.5-mini-instruct":           "3.8B",
    "meta-llama/Llama-3.1-8B-Instruct":          "8.03B",
    "meta-llama/Llama-3.1-70B-Instruct":         "70B",
    "meta-llama/Llama-3.2-1B-Instruct":          "1B",
    "meta-llama/Llama-3.2-3B-Instruct":          "3B",
    "microsoft/phi-4":                           "14.7B",
    "mistralai/Codestral-22B-v0.1":              "22.2B",
    "deepseek-ai/DeepSeek-R1-Distill-Llama-8B":  "8.03B",
    "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B":  "32.8B",
    "deepseek-ai/DeepSeek-R1-Distill-Llama-70B": "70.6B",
    "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B": "1.5B",
    "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B":  "14.8B",
    "gpt-4o-mini":                               "8B",
    "Qwen/Qwen2.5-Coder-32B-Instruct":           "32.8B",
    "Qwen/QwQ-32B":                              "32.8B",
    "deepseek-ai/deepseek-coder-33b-instruct":   "33.3B",
    "deepseek-ai/DeepSeek-R1-0528-Qwen3-8B":     "8.19B",
    "Qwen/Qwen2.5-72B-Instruct":                 "72B",
    "Qwen/Qwen3-32B":                            "32.8B",
    "WizardLMTeam/WizardLM-70B-V1.0":            "70B"
}


model_categories = {
    "01-ai/Yi-Coder-9B-Chat":                   "Code Generation",
    "Qwen/Qwen3-4B":                            "General Instruction",
    "Qwen/Qwen3-8B":                            "General Instruction",
    "Qwen/Qwen3-32B":                           "General Instruction",
    "bigcode/starcoder2-15b-instruct-v0.1":     "Code Generation",
    "codellama/CodeLlama-70b-Python-hf":        "Code Generation",
    "codellama/CodeLlama-34b-Instruct-hf":      "Code Generation",
    "mistralai/Codestral-22B-v0.1":             "Code Generation",
    "Qwen/Qwen2.5-Coder-32B-Instruct":          "Code Generation",
    "deepseek-ai/deepseek-coder-33b-instruct":  "Code Generation",
    "google/codegemma-7b-it":                   "Code Generation",
    "microsoft/Phi-3-mini-128k-instruct":       "General Instruction",
    "microsoft/Phi-3.5-mini-instruct":          "General Instruction",
    "microsoft/phi-4":                          "General Instruction",
    "meta-llama/Llama-3.1-8B-Instruct":         "General Instruction",
    "meta-llama/Llama-3.1-70B-Instruct":        "General Instruction",
    "meta-llama/Llama-3.2-1B-Instruct":         "General Instruction",
    "meta-llama/Llama-3.2-3B-Instruct":         "General Instruction",
    "WizardLMTeam/WizardLM-70B-V1.0":           "General Instruction",
    "deepseek-ai/DeepSeek-R1-Distill-Llama-8B": "Reasoning Distilled",
    "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B": "Reasoning Distilled",
    "deepseek-ai/DeepSeek-R1-Distill-Llama-70B":"Reasoning Distilled",
    "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B":"Reasoning Distilled",
    "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B": "Reasoning Distilled",
    "gpt-4o-mini":                              "Reasoning",
    "Qwen/QwQ-32B":                             "Reasoning",
    "Qwen/Qwen2.5-72B-Instruct":                "Reasoning",
    "deepseek-ai/DeepSeek-R1-0528-Qwen3-8B":    "Reasoning"
}